
version: '3.8'
services:
  mongo:
    image: mongo
    ports:
      - "27017:27017"

  redis:
    image: redis
    ports:
      - "6379:6379"

  receiver-service:
    build: ./receiver-service
    ports:
      - "3000:3000"
    depends_on:
      - mongo
      - redis

  listener-service:
    build: ./listener-service
    depends_on:
      - mongo
      - redis
